# Determine # most freqeunt K-mers within input

def count (input, pattern):
    counter = 0 
    for i in range(0,len(input)):
        length = len(pattern) 
        if input[i:i+length] == pattern:
           counter += 1
    return counter


def kcount (input, k):
    count_dic = {}
    countArr = []
    for i in range(0,len(input)):
        temp_pattern = input[i:i+k]
        if len(temp_pattern) == k:
            counting = count(input,temp_pattern)
            count_dic[temp_pattern] = counting 
    for key in count_dic.keys():
        if count_dic[key] == max(count_dic.values()):
           countArr.append(key)
    return countArr

text = "CGGAGAGCTCGGAGAGCTCGTGGATAACTGCTCGACGGAGAGCTCTGCTCGACTGCTCGACTGCTCGATTCGCTGAATCTGCTCGACGTGGATAATTCGCTGAATTTCGCTGAATTTCGCTGAATCTGCTCGAAGTGATTCCCGTGGATAATTCGCTGAATCTGCTCGACGGAGAGCTCGGAGAGCTTTCGCTGAATAGTGATTCCTTCGCTGAATAGTGATTCCCGTGGATAACGGAGAGCTCTGCTCGACGGAGAGCTAGTGATTCCCTGCTCGACTGCTCGACGGAGAGCTCTGCTCGACGTGGATAACTGCTCGACTGCTCGACGTGGATAACGGAGAGCTCGGAGAGCTAGTGATTCCTTCGCTGAATAGTGATTCCCGTGGATAAAGTGATTCCCTGCTCGACGGAGAGCTCGGAGAGCTTTCGCTGAATTTCGCTGAATCGTGGATAACTGCTCGACGTGGATAACGTGGATAACTGCTCGATTCGCTGAATCGGAGAGCTCGTGGATAACTGCTCGAAGTGATTCCTTCGCTGAATAGTGATTCCCGTGGATAATTCGCTGAATCTGCTCGACGGAGAGCTCTGCTCGATTCGCTGAATCTGCTCGACGGAGAGCTTTCGCTGAATAGTGATTCCTTCGCTGAATCGTGGATAACGTGGATAACGGAGAGCTCGGAGAGCTCGGAGAGCTTTCGCTGAATAGTGATTCCAGTGATTCCCGGAGAGCTTTCGCTGAATCGGAGAGCTCTGCTCGACTGCTCGACGGAGAGCTTTCGCTGAATAGTGATTCCCGTGGATAACGTGGATAATTCGCTGAATCGGAGAGCTCGGAGAGCTCGTGGATAACTGCTCGACGGAGAGCTCGTGGATAACGTGGATAACTGCTCGATTCGCTGAATCGTGGATAAAGTGATTCCCTGCTCGA"
print(kcount(text,14))
