# Find distinct k-mers forming (L, t)-clumps in Genome.

def count (input, pattern, L, c):
    counter = 0 
    for i in range(c,L+c):
        length = len(pattern) 
        if input[i:i+length] == pattern:
           counter += 1
    return counter


def kcount (input, k, L, t):
    countArr = []
    for i in range(0,len(input)):
        temp_pattern = input[i:i+k]
        if len(temp_pattern) == k:
            counting = count(input,temp_pattern, L, i)
            if counting == t:
               countArr.append(temp_pattern)
    return countArr

text = "TAGTCTTGTGCAGTATGTCGCTGAAATGTCTTAAATAGCCGAACATAGAGAGTATAAAATGACTTATTGTTGGCAAAGCAGTGTGCAAGTGATAAGGCACTCGTCAATACCAGCTTTTCGCTGTATGACATCCGATTATATAGCTGTAAAACGGCTAGCTGTAGTATGAGCGTGTCAGCCATAGCACATTCGTTGAAAAGGATGGTTATCTTCTGTCAATGTGTTACTTCGCCGACACACAATCGGTATGTGAAAGCTGGGTTGGTTAGTATGACTCAGAGGGAGAGGTCAGAGGGGGGGTTCAAACTCGTCGATCAGGAACCCTATAGTTAGGTTAGTTAGCGTATTTCCAAGCTAGCTCGAAGCCCTTTTTCGGCACCTACATTCACTGGTAGCCACAGCACTCCACCCAAGTACGAAATTCAATCAATGTAACCGCTTATCTACCCGCGTGTGATTAAATTAAGAGGGATTATTAAGAGGCCAGATCCCCGCTTGTGTACAACCTTTCGGAGACCCCCGAACCGAGGCATCACAGCAAGTATCATGCCATCTTCAGGCTGATTTGTACCGCAGATAGCAATCTAGTAACTGACATGTTGGATGCAACGTAAGAGGGGCTCGCAACGAGTGTACCTGCTTGGCTTGTTGGTTGTTGTTGTTGATTAAGATGAATTTTCGCACCGGAGGACCACCGGACAGTACAGTCAGTCCTTTAGTCCTTTTCATACGCAATCACTCGTCTGTGGTACCAGTAGAGTCCAGACGCCCACACTCCTGCAATACGAAACATATGTCACTCGAATATCCACGGCGCCGAGCTTTGTTCACAAGTCTGTACAAGACAAGTCTCTTAACTCCGTGCATTTATTCCGTGCGTGCATTACCTCCGGAAAATCAGGAGGGAAGGGAACCGAACCAGCCTAGGCTAAAAATGAGAAATGAGATGAGAAATGAGATCGCACTACGACTTAAACGGTCGCCGAGGTGGGGTCGGTCGCCGCTTATCCCACATAAACGCGATTCCCTACTGCGTGCCCCATCAGATTGCAAGCGACAGACTTGGGTAATAAGGGCGAGCGTCCACTGAACTGTTGAACTGTAACTGTCCGTCGGCTAGTTATTCGCACTAAGATGCCAACGGACGCCTATCTCGCGGCATGATAAACGTGAGGTCCATAGACCTATTCGGACAACCTTAAGCCTGTTTACAGACAAGCCCAAGACCGAGAGCTTCGTAAGCAATTTAAGTACGATTCGTAGCAATTTTATACAGTCGTTGTTACTAAGTTCACAAATCCGTATGAACGCTGGCTCGGAACGCTGGAACGCTGGGACCAGCTAACCCTCAAGTTAGGATTCTTGCAGCCGCGGGGAGAAAGGGGAGAAAGAGAAAGGTACTTCAAGTATATAAGTTCAAGTATTATATCTTGGAACCGTAGATTTAGTTCGCCGTCAGTCGGCGAACAAGTTCTTTACATACACTCTTTCTTTACAAAGCATGCAAGATTACGACTGCGCTTTCATTTCTTCGCAGCAGACATCGTCCGCAACACACACGCAACAACTGCTGTACTAATTAAGCGACGCACAGACTACTCCCAGTGAACCGCGTTGTAGAATGTGGGCACGATATGAATTAATGACGAGCGATCGTATTTCCACCACCTTTAGCAGGCATCCTTGTCCTTGGAGGATTCCTTGGAGGACAGACCCACACAAACACGTATCCATAGCGCATGTACTCATAATTACGTCAGAGGGCACAGCCGACCGCTAGCGCGCTAGCGCGCTAGCGCGCTAGCGCGCTAGCGCGCTAGCGC"
# print(kcount(text,8,30,3))

my_file = open("E_coli.txt")
file_contents = my_file.read()
print (len(file_contents))
print (file_contents)
print(kcount(file_contents,9,500,3))